# Generated by Django 4.2.7 on 2023-12-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
