# Generated by Django 4.2.6 on 2023-12-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
